title: Enoch Cheung # your name (or website title) here
#logo: "/images/dp2022.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <sup>
  <b>Profile</b><br>
  Business and analytics professional with 5+ years of experience translating digital marketing and product data into decision support through dashboards and performance analysis. 
  <br>Recently completed an MSc BA (Health) with training in evidence synthesis to analyse how social and digital factors influence adoption and implementation withinin healthcare contexts.  <br><br>
  <b>Domain</b><br>
  Digital analytics in health and healthcare contexts
  <br>(Interest in prevention and primary care–oriented health solutions)
  <br><br>
  <b>Skills</b><br>
  <b>Technical:</b> GA4 · GTM · Google Ads · SEO · Search Console · Looker Studio · Tableau <br>
  <b>Research:</b> Systematic literature review · Decision-analytic modelling
  <br><br>
  <a href="https://www.linkedin.com/in/enoch-cheung-hk/">View My LinkedIn</a>
  </sup>

theme: jekyll-theme-minimal
google_analytics: 347208407 # your Google Analytics tracking ID here
